// src/vue-echarts.vue
<template>
  <div ref="container">
    vue echarts
  </div>
</template>

<script>
  import echarts from 'echarts'

  export default {
    props: ['option', 'loading'],
    //注意时机，在挂载之后
    mounted() {
      //  用ref拿到dom元素
      const container = this.$refs.container
      const width = document.documentElement.clientWidth
      container.style.width = `${width * 0.8}px`
      container.style.height = `${width * 0.8 * 1.2}px`

      //挂到实例上
      this.chart = echarts.init(container)
      this.chart.setOption(this.option)

    },
    //主要是监听变化 option 和 loading
    watch: {
      option(){
        if(this.loading){return}
        this.chart.setOption(this.option)
      },
      loading(){
        if(this.loading) {
          this.chart.showLoading()
        } else {
          this.chart.hideLoading()
        }
      }

    }
  }
</script>

// src/react-echarts.jsx
import React, {useEffect, useRef} from 'react'
import echarts from 'echarts'

export function ReactEcharts(props) {

  //ref标记元素
  const container = useRef(null)

  const chart = useRef(null)
  //useEffect，根据数组模拟第一次，update，指定update
  //[]  相当于 mounted，因为第一次总是触发，后面就是看数组的元素有没有变化
  useEffect(() => {
    const width = document.documentElement.clientWidth
    container.current.style.width = `${width * 0.8}px`
    container.current.style.height = `${width * 0.8 * 1.2}px`
    chart.current = echarts.init(container.current)
  }, [])
  //监听option变化
  useEffect(() => {
    chart.current.setOption(props.option)
  }, [props.option])

  // useEffect(() => {
  //   if(props.loading){
  //     chart.current.showLoading()
  //   } else {
  //     chart.current.hideLoading()
  //   }
  // },[props.loading])
  return (
    <div ref={container}/>
  )
}
